In [143]:
from formatted_code import Gymnastic_Data_Analyst
import numpy as np

Load_data = True
if Load_data:
    data = Gymnastic_Data_Analyst(load_dir="data/formatted_data/")
else:
    data = Gymnastic_Data_Analyst(
        data_dir="data/data_2022_2023.csv", data_name="gymnasts")
    data.save_all_data("data/formatted_data/")
summary_data = data.summary_for_each_country_by_gender(
    data_name="summary_men_gymnasts", country_name="COL", k_top_for_apparatus=5, k_top_for_score=2)
# Store the summary_data into a text file
with open("data/summary_data.txt", "w") as f:
    f.write(str(summary_data))

# Get a list of countries with the most number of gymnasts
num_of_gymnasts = {}
for country in data.data["gymnasts"]["Country"].unique():
    num_of_gymnasts[country] = data.data["gymnasts"].loc[data.data["gymnasts"]
        ["Country"] == country].shape[0]
sorted_num_of_gymnasts = sorted(
    num_of_gymnasts.items(), key=lambda x: x[1], reverse=True)
# Select the top 12 countries
top_24_countries = [country for country,
    num in sorted_num_of_gymnasts[:24]]
# Let's select 12 countries from "summary_men_gymnasts"
men_countries = top_24_countries[:12]
# Let's select 12 countries from "summary_women_gymnasts",
women_countries = top_24_countries[:12]

# Use data.summary_for_each_country_by_gender method to get the summary data for each country, and append the summary data to the summary_data
qual_men_12_team = {}
max_num_of_gymnasts = 5
for men_country in men_countries:
    # Get the summary data for each country by data.summary_for_each_country_by_gender method
    summary_data_for_country = data.summary_for_each_country_by_gender(
        data_name="summary_men_gymnasts", country_name=men_country, k_top_for_apparatus=5, k_top_for_score=2, max_num_of_gymnasts=max_num_of_gymnasts)
    # Create a random matrix of size (max_num_of_gymnasts, len(data.men_apparatus_ls)), where each column has four 1's and the rest are 0's
    matrix = np.zeros((max_num_of_gymnasts, len(data.men_apparatus_ls)))
    
    # choose 1 to attend individual all-around
    random_index = np.random.randint(matrix.shape[0])
    # Set all elements in the randomly selected person row to 1
    matrix[random_index, :] = 1

    # choose another 3 for each apparatus
    gymnast_index_list = list(range(max_num_of_gymnasts))
    gymnast_index_list.remove(random_index)

    for i in range(len(data.men_apparatus_ls)):
        ones_indices = np.random.choice(
            gymnast_index_list, size=3, replace=False)
        matrix[ones_indices, i] = 1
    # Add the matrix to the summary_data_for_country['data'] DataFrame and add columns according to the apparatus list
    for j, apparatus in enumerate(data.men_apparatus_ls):
        summary_data_for_country[men_country]['data'][apparatus+ \
            "_qual_participation"] = matrix[:, j]
    # append the matrix as an item in the dictionary
    summary_data_for_country[men_country]['qual_participation'] = matrix
    # Append the summary data to the summary_data
    qual_men_12_team.update(summary_data_for_country)



# For women gymnasts, do the same
qual_women_12_team = {}
max_num_of_gymnasts = 5
for women_country in women_countries:
    # Get the summary data for each country by data.summary_for_each_country_by_gender method
    summary_data_for_country = data.summary_for_each_country_by_gender(
        data_name="summary_women_gymnasts", country_name=women_country, k_top_for_apparatus=4, k_top_for_score=2, max_num_of_gymnasts=max_num_of_gymnasts)
    # Create a random matrix of size (num_gymnasts, len(data.women_apparatus_ls)), where each row has four 1's and the rest are 0's
    matrix = np.zeros((max_num_of_gymnasts, len(data.women_apparatus_ls)))

    # choose 1 to attend individual all-around
    random_index = np.random.randint(matrix.shape[0])
    # Set all elements in the randomly selected person row to 1
    matrix[random_index, :] = 1

    # choose another 3 for each apparatus
    gymnast_index_list = list(range(max_num_of_gymnasts))
    gymnast_index_list.remove(random_index)

    for i in range(len(data.women_apparatus_ls)):
        ones_indices = np.random.choice(
            gymnast_index_list, size=3, replace=False)
        matrix[ones_indices, i] = 1
    # Add the matrix to the summary_data_for_country['data'] DataFrame and add columns according to the apparatus list
    for j, apparatus in enumerate(data.women_apparatus_ls):
        summary_data_for_country[women_country]['data'][apparatus+ \
            "_qual_participation"] = matrix[:, j]
    # append the matrix as an item in the dictionary
    summary_data_for_country[women_country]['qual_participation'] = matrix
    # Append the summary data to the summary_data
    qual_women_12_team.update(summary_data_for_country)




# Let's select 12 countries that are different from the previous 12 countries
men_countries_12 = top_24_countries[-12:]
women_countries_12 = top_24_countries[-12:]
qual_men_36_team = {}
max_num_of_gymnasts = 3
for men_country in men_countries:
    # Get the summary data for each country by data.summary_for_each_country_by_gender method
    summary_data_for_country = data.summary_for_each_country_by_gender(
        data_name="summary_men_gymnasts", country_name=men_country, k_top_for_apparatus=4, k_top_for_score=3, max_num_of_gymnasts=max_num_of_gymnasts)
   
    # Create a random matrix of size (max_num_of_gymnasts, len(data.men_apparatus_ls))
    matrix = np.random.randint(0, 2, (max_num_of_gymnasts, len(data.men_apparatus_ls)))
    # choose 1 to attend individual all-around
    random_index = np.random.randint(matrix.shape[0])
    # Set all elements in the randomly selected person row to 1
    matrix[random_index, :] = 1
    # Add the matrix to the summary_data_for_country['data'] DataFrame and add columns according to the apparatus list
    for j, apparatus in enumerate(data.men_apparatus_ls):
        summary_data_for_country[men_country]['data'][apparatus+ \
            "_qual_participation"] = matrix[:, j]
    summary_data_for_country[men_country]['qual_participation'] = matrix
    # Append the summary data to the summary_data
    qual_men_36_team.update(summary_data_for_country)



# For women gymnasts, do the same
qual_women_36_team = {}
max_num_of_gymnasts = 3
for women_country in women_countries:
    # Get the summary data for each country by data.summary_for_each_country_by_gender method
    summary_data_for_country = data.summary_for_each_country_by_gender(
        data_name="summary_women_gymnasts", country_name=women_country, k_top_for_apparatus=4, k_top_for_score=3, max_num_of_gymnasts=max_num_of_gymnasts)
    # Create a random matrix of size (max_num_of_gymnasts, len(data.men_apparatus_ls))
    matrix = np.random.randint(0, 2, (max_num_of_gymnasts, len(data.women_apparatus_ls)))
    # choose 1 to attend individual all-around
    random_index = np.random.randint(matrix.shape[0])
    # Set all elements in the randomly selected person row to 1
    matrix[random_index, :] = 1
    # Add the matrix to the summary_data_for_country['data'] DataFrame and add columns according to the apparatus list
    for j, apparatus in enumerate(data.women_apparatus_ls):
        summary_data_for_country[women_country]['data'][apparatus+ \
            "_qual_participation"] = matrix[:, j]
    summary_data_for_country[women_country]['qual_participation'] = matrix
    # Append the summary data to the summary_data
    qual_women_36_team.update(summary_data_for_country)


/Users/ruixiaowang/Desktop/Yale/2023 Fall/Case Studies/Gym/Gym/formatted_code.py:693: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["apparatus_name"+"_score"] = pd.to_numeric(data[apparatus_name+"_score"])
/Users/ruixiaowang/Desktop/Yale/2023 Fall/Case Studies/Gym/Gym/formatted_code.py:693: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["apparatus_name"+"_score"] = pd.to_numeric(data[apparatus_name+"_score"])
/Users/ruixiaowang/Desktop/Yale/2023 Fall/Case Studies/Gym/Gym/formatted_code.py:693: Sett

In [2]:
# Store the summary_data into a txt file
file_name = 'tmp.txt'
with open(file_name, 'w') as f:
    f.write("Qualification Men's 12 Team\n")
    for key, value in qual_men_12_team.items():
        f.write(f"{key}: {value}\n")
    f.write("\nQualification Women's 12 Team\n")
    for key, value in qual_women_12_team.items():
        f.write(f"{key}: {value}\n")

In [6]:
# qual_women_36_team， qual_women_36_team， qual_women_12_team， qual_women_12_team
# Replace 'COL' with the country name you want to get the qual_participation matrix for
country_name = top_24_countries[0]

# Get the qual_participation matrix for the specified country
qual_participation_matrix = qual_men_12_team[country_name]['qual_participation']
print(qual_participation_matrix)
# Get the qual_participation matrix for the specified country
qual_apparatus_score = qual_men_12_team[country_name].
print(qual_apparatus_score)

[[0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0. 0.]]
    LastName FirstName Gender Country                      Date  \
266   fraser       joe      m     GBR  29 Oct 2022 - 6 Nov 2022   
240   jarman      jake      m     GBR  29 Oct 2022 - 6 Nov 2022   
196   regini   giarnni      m     GBR  29 Oct 2022 - 6 Nov 2022   
109  tulloch  courtney      m     GBR  29 Oct 2022 - 6 Nov 2022   

                                           Competition    Round  \
266  2022 51st FIG Artistic Gymnastics World Champi...  AAfinal   
240  2022 51st FIG Artistic Gymnastics World Champi...  AAfinal   
196  2022 51st FIG Artistic Gymnastics World Champi...    final   
109  2022 51st FIG Artistic Gymnastics World Champi...    final   

               Location  Rank  D_Score  ...  PH_num_of_samples   FX_score  \
266  Liverpool, England  12.0      5.7  ...                  9  13.624750   
240  Liverpool, England   3.0      6.7  ...                 11  14.2

In [210]:
def qual_result_36_country_all_around_helper(qual_participation_matrix, qual_apparatus_score_matrix): 
    """
    individual_all_around_qual_score: dict {name:sum of six apparatus score} 
    """  
    # first identify row with all ones (those who attended all apparatus)
    rows_with_ones = np.all(qual_participation_matrix == 1, axis=1)
    total_score = np.sum(qual_apparatus_score_matrix[rows_with_ones], axis = 1)
    # print(qual_apparatus_score_matrix)
    # print(rows_with_ones)
    # print(total_score)
    # Get the indices of rows with all 1's
    indices = np.where(rows_with_ones)[0]
    # an individual_all_around_qual_score dict {gymnast_name: total_score}
    individual_all_around_qual_score = {idx:total_score[i] for i, idx in enumerate(indices)}
    
    return individual_all_around_qual_score
   
# individual all around for team_36 (12 teams)

def qual_result_36_country_all_around(team_36, apparatus_ls):
    """
    return a dictionary of {(country, name): sum of six score} in team_36 (12 countries)
    """
    individual_all_around_result = dict() # (country, name): sum of six score
    for country_name in team_36:
        team_36[country_name]["individual_all_around_qual_score"] = dict()
        qual_participation_matrix = team_36[country_name]['qual_participation']
        qual_apparatus_score_matrix = list()
        for j, apparatus in enumerate(apparatus_ls):
            qual_apparatus_score = team_36[country_name][apparatus]["apparatus_name_score"] # top k score in this apparatus
            qual_apparatus_score_matrix.append(qual_apparatus_score)
        qual_apparatus_score_matrix = np.nan_to_num(np.array(qual_apparatus_score_matrix).T) # replace all nan with 0 score
        #print(qual_apparatus_score_matrix)
          
        individual_all_around_qual_score = qual_result_36_country_all_around_helper(qual_participation_matrix, qual_apparatus_score_matrix)
        for idx, score in individual_all_around_qual_score.items():
            individual_all_around_result[(country_name, idx)] = score
            # add to each country's dict
            team_36[country_name]["individual_all_around_qual_score"][idx] = score 
    return individual_all_around_result
                
apparatus_ls = data.men_apparatus_ls
team_36 = qual_men_36_team
qual_result_36_country_all_around(team_36, apparatus_ls)

{('GBR', 0): 85.15809941520467,
 ('ESP', 1): 80.07616666666667,
 ('TUR', 2): 39.5,
 ('ITA', 1): 38.754,
 ('GER', 2): 25.272399999999998,
 ('AUS', 2): 0.0,
 ('FRA', 1): 54.34866666666667,
 ('HUN', 0): 81.57960995670996,
 ('JPN', 0): 86.49953333333333,
 ('NED', 1): 40.66633333333333,
 ('FIN', 2): 12.8,
 ('UKR', 1): 77.22}

In [211]:
def qual_result_12_country_all_around(qual_participation_matrix, qual_apparatus_score_matrix):
    
    """
    individual_all_around_qual_score: dict {name:sum of six apparatus score}
    team_all_around_qual_score: float, sum of [sum of top 3 scores of each apparatus]
    team_all_around_binary_matrix: 0,1 matrix (np.array), team_all_around top 3 gymnasts for each apparatus
    
    """
    # calculate qualifying round score for each apparatus (choose top 3)
    qual_score_matrix = qual_participation_matrix*qual_apparatus_score_matrix
    top_3_values = np.partition(-qual_score_matrix, 3, axis=0)[:3, :]
    # Compute the indices of top 3 values
    top_3_indices = np.argpartition(-qual_score_matrix, 3, axis=0)[:3, :]
    # Create a binary matrix indicating the positions of the top 3 elements
    team_all_around_binary_matrix = np.zeros(qual_score_matrix.shape)
    for i in range(top_3_indices.shape[1]):  # for each column
        team_all_around_binary_matrix[top_3_indices[:, i], i] = 1
    # Convert top 3 values to positive (since we negated them earlier)
    top_3_values = -top_3_values
    # Summing up the top 3 values in each column
    team_all_around_qual_score = np.sum(np.sum(top_3_values, axis=0))
    
    
    # individual all around
    # first identify row with all ones (those who attended all apparatus)
    rows_with_ones = np.all(qual_participation_matrix == 1, axis=1)
    total_score = np.sum(qual_apparatus_score_matrix[rows_with_ones], axis = 1)
    # print(qual_apparatus_score_matrix)
    # print(rows_with_ones)
    # print(total_score)
    # Get the indices of rows with all 1's
    indices = np.where(rows_with_ones)[0]
    print(indices)
    # an individual_all_around_qual_score dict {gymnast_name: total_score}
    individual_all_around_qual_score = {idx:total_score[i] for i, idx in enumerate(indices)}
    
    return team_all_around_qual_score, team_all_around_binary_matrix, individual_all_around_qual_score
    # print("\nTop 3 Values:\n", top_3_values)
    # print("\nBinary Matrix Indicating Top 3 Positions:\n", binary_matrix)
    # print("\nSum of Top 3 Values in Each Column:\n", sum_top_3_values)




# prediction starts here

In [202]:
from collections import defaultdict
teams_12 = [qual_men_12_team, qual_women_12_team]
teams_36 = [qual_men_36_team, qual_women_36_team]



def all_around_result(teams, apparatus_ls):
    """
    teams: [qual_men_12_team, qual_men_36_team] or [qual_women_12_team, qual_women_36_team]
    apparatus_ls: data.men_apparatus_ls or data.women_apparatus_ls
    """
    
    ######## team all around 
    team_12_all_around_result = dict()
    individual_all_around_result = dict() # (country, name): sum of six score
    team_12 = teams[0]
    team_36 = teams[1]
    for country_name in team_12:
        qual_participation_matrix = team_12[country_name]['qual_participation']
        qual_apparatus_score_matrix = list()
        for j, apparatus in enumerate(apparatus_ls):
            ###scores don't match!!!!!!!!!!!
            qual_apparatus_score = team_12[country_name][apparatus]["apparatus_name_score"] # top k score in this apparatus
            qual_apparatus_score_matrix.append(qual_apparatus_score)
        qual_apparatus_score_matrix = np.nan_to_num(np.array(qual_apparatus_score_matrix).T) # replace all nan with 0 score
        
        
        # individual and team_12 all around qual results
        sum_top_3_values, team_12_all_around_binary_matrix, individual_all_around_qual_score = qual_result_12_country_all_around(qual_participation_matrix, qual_apparatus_score_matrix)
        team_12[country_name]["sum_top_3_values"] = sum_top_3_values
        team_12[country_name]["team_12_all_around_binary_matrix"] = team_12_all_around_binary_matrix
        team_12[country_name]["individual_all_around_qual_score"] = individual_all_around_qual_score
        team_12[country_name]["qual_team_12_all_around_score"] = qual_apparatus_score_matrix
        team_12_all_around_result[country_name] = sum_top_3_values
        # team_12 all around ranking: Get the top 8 countries
        team_all_around_sorted_countries = sorted(team_12_all_around_result.items(), key=lambda x: x[1], reverse=True)
        top_8_countries = [country for country, score in team_all_around_sorted_countries[:8]]


        for idx, score in individual_all_around_qual_score.items():
            individual_all_around_result[(country_name, idx)] = score
            if country_name == "JPN":
                print(country_name, idx, score)
        
            
    ######## individual_all_around qual result  
    # add in team_36
    team_36_individual_all_around = qual_result_36_country_all_around(team_36, apparatus_ls)
    individual_all_around_result.update(team_36_individual_all_around)
    sorted_athletes = sorted(individual_all_around_result.items(), key=lambda x: x[1], reverse=True)
    
    # select top 24
    # Dictionary to hold the top 24 athletes, ensuring not more than 2 athletes per country
    top_24_athletes = {}
    
    # record number of atheletes who gets into individual final round, should be <= 2
    country_count = defaultdict(int)
    for athlete, score in sorted_athletes:
        country, idx = athlete
        
        # Ensure not more than 2 athletes per country are selected
        if country_count[country] < 2:
            top_24_athletes[athlete] = score
            country_count[country] += 1
        
        # Stop when 24 athletes have been selected
        if len(top_24_athletes) == 24:
            break
    individual_all_around_top_24_athletes = sorted(top_24_athletes.items(), key=lambda x: x[1], reverse=True)
    top_24_athletes = [i for i, score in individual_all_around_top_24_athletes[:24]]
    
    return  team_all_around_sorted_countries,top_8_countries, individual_all_around_top_24_athletes, top_24_athletes

# individual all around ranking: Get the top 24 countries
    
# each apparatus ranking
team_all_around_sorted_countries_score,top_8_countries, individual_all_around_top_24_athletes, top_24_athletes = all_around_result([qual_men_12_team, qual_men_36_team], data.men_apparatus_ls)
print(len(top_8_countries))
print(len(top_24_athletes))
print(top_8_countries)
print(top_24_athletes)

[0 1 3]
[0]
[1 4]
[0]
[0 1]
[3]
[2 4]
[0]
[1 2]
JPN 1 85.22515
JPN 2 83.91706666666667
[0 1 2]
[0 2]
[2 3]
{('GBR', 0): 85.15809941520467, ('GBR', 1): 83.67563080048605, ('GBR', 3): 54.2291, ('ESP', 0): 83.07368888888888, ('TUR', 1): 81.92324761904763, ('TUR', 4): 25.681333333333335, ('ITA', 0): 84.98269444444445, ('GER', 0): 83.52860714285714, ('GER', 1): 80.94728571428571, ('AUS', 3): 0.0, ('FRA', 2): 80.32986666666667, ('FRA', 4): 12.166, ('HUN', 0): 81.57960995670996, ('JPN', 1): 85.22515, ('JPN', 2): 83.91706666666667, ('NED', 0): 83.27141666666667, ('NED', 1): 40.66633333333333, ('NED', 2): 78.87066666666666, ('FIN', 0): 80.39499999999998, ('FIN', 2): 12.8, ('UKR', 2): 78.10645454545454, ('UKR', 3): 75.22802631578946, ('ESP', 1): 80.07616666666667, ('TUR', 2): 39.5, ('ITA', 1): 38.754, ('GER', 2): 25.272399999999998, ('AUS', 2): 0.0, ('FRA', 1): 54.34866666666667, ('JPN', 0): 86.49953333333333, ('UKR', 1): 77.22}
8
23
['NED', 'ESP', 'TUR', 'GER', 'HUN', 'UKR', 'JPN', 'GBR']
[('JP

In [258]:
from collections import defaultdict
teams_12 = [qual_men_12_team, qual_women_12_team]
teams_36 = [qual_men_36_team, qual_women_36_team]

def predict(apparatus, dict_of_qual_result):   
    sorted_athletes = sorted(dict_of_qual_result.items(), key=lambda x: x[1], reverse=True)
    # Dictionary to hold the top 24 athletes, ensuring not more than 2 athletes per country
    top_8_athletes = {}
    # record number of atheletes who gets into individual final round, should be <= 2
    country_count = defaultdict(int)
    for athlete, score in sorted_athletes:
        country, idx = athlete
        
        # Ensure not more than 2 athletes per country are selected
        if country_count[country] < 2:
            top_8_athletes[athlete] = score
            country_count[country] += 1
        
        # Stop when 24 athletes have been selected
        if len(top_8_athletes) == 8:
            break
    individual_all_around_top_24_athletes = sorted(top_8_athletes.items(), key=lambda x: x[1], reverse=True)
    top_8_athletes = [i for i, score in sorted_athletes[:8]]
    # add noise to final round     
    dict_of_final_result = {i: score+np.random.normal(0,1) for i, score in sorted_athletes[:8]}
    sorted_athletes_final = sorted(dict_of_final_result.items(), key=lambda x: x[1], reverse=True)
    top_3_athletes = [i for i, score in sorted_athletes_final[:3]]

    return top_8_athletes, sorted_athletes, top_3_athletes, sorted_athletes_final

def each_apparatus_result(teams, apparatus_ls):
    """
    teams: [qual_men_12_team, qual_men_36_team] or [qual_women_12_team, qual_women_36_team]
    apparatus_ls: data.men_apparatus_ls or data.women_apparatus_ls
    """
    team_12_all_around_result = dict()
    individual_all_around_result = dict() # (country, name): sum of six score
    team_12 = teams[0]
    team_36 = teams[1]
    apparatus_ls_dict = dict()
    for apparatus in apparatus_ls:
        apparatus_ls_dict[apparatus] = dict()
        
    for country_name in team_12:
        qual_participation_matrix = team_12[country_name]['qual_participation']
        qual_apparatus_score_matrix = list()
        for j, apparatus in enumerate(apparatus_ls):
            #print(apparatus)
            #qual_apparatus_score = team_12[country_name][apparatus].keys() #[apparatus+ "_qual_participation"]
            
            ###scores don't match!!!!!!!!!!!
            qual_apparatus_score = team_12[country_name][apparatus]["apparatus_name_score"] # top k score in this apparatus
            qual_apparatus_score_matrix.append(qual_apparatus_score)
        qual_apparatus_score_matrix = np.nan_to_num(np.array(qual_apparatus_score_matrix).T) # replace all nan with 0 score
        each_apparatus_participation_score = qual_apparatus_score_matrix*qual_participation_matrix
        for col in range(len(apparatus_ls)):
            for row in range(each_apparatus_participation_score.shape[0]):
                if each_apparatus_participation_score[row,col] != 0:
                    apparatus_ls_dict[apparatus_ls[col]][(country_name, row)] = each_apparatus_participation_score[row,col]
    #add team_36
    for country_name in team_36:
        qual_participation_matrix = team_36[country_name]['qual_participation']
        qual_apparatus_score_matrix = list()
        for j, apparatus in enumerate(apparatus_ls):
            ###scores don't match!!!!!!!!!!!
            qual_apparatus_score = team_36[country_name][apparatus]["apparatus_name_score"] # top k score in this apparatus
            qual_apparatus_score_matrix.append(qual_apparatus_score)
        qual_apparatus_score_matrix = np.nan_to_num(np.array(qual_apparatus_score_matrix).T) # replace all nan with 0 score
        each_apparatus_participation_score = qual_apparatus_score_matrix*qual_participation_matrix
        for col in range(len(apparatus_ls)):
            for row in range(each_apparatus_participation_score.shape[0]):
                if each_apparatus_participation_score[row,col] != 0:
                    apparatus_ls_dict[apparatus_ls[col]][(country_name, row)] = each_apparatus_participation_score[row,col]
    final_result_all_apparatus_dict = dict()                
    for apparatus in apparatus_ls:
        top_8_athletes, sorted_athletes, top_3_athletes, sorted_athletes_final = predict(apparatus, apparatus_ls_dict[apparatus]) #dict_of_qual_result = {(country, name): score} 
        #print(apparatus, top_8_athletes, sorted_athletes
        final_result_all_apparatus_dict[apparatus] = [top_8_athletes, sorted_athletes, top_3_athletes, sorted_athletes_final]
    
    return final_result_all_apparatus_dict

# individual all around ranking: Get the top 24 countries
teams = [qual_men_12_team, qual_men_36_team]    
final_result_all_apparatus_dict = each_apparatus_result(teams, apparatus_ls)


In [229]:
team12 = qual_men_12_team
team36 = qual_men_36_team


def team_all_around_result(team, apparatus_ls):
    team_12_all_around_final_result = dict()
    ######### predict final round result for team all around
    for country in top_8_countries:
        top3_binary_matrix = team12[country_name]["team_12_all_around_binary_matrix"]
        noise = np.random.normal(0, 1, top3_binary_matrix.shape)
        team12[country_name]["team_12_all_around_final_result"] = top3_binary_matrix*(team12[country_name]["qual_team_12_all_around_score"]+noise)
        team12[country_name]["team_12_all_around_final_total_score"] = np.sum(np.sum(team12[country_name]["team_12_all_around_final_result"], axis=0))
        
        team_12_all_around_final_result[country] = team12[country_name]["team_12_all_around_final_total_score"]
    team_all_around_sorted_countries = sorted(team_12_all_around_final_result.items(), key=lambda x: x[1], reverse=True)
    top_3_countries = [country for country, score in team_all_around_sorted_countries[:3]]
    return top_3_countries,team_all_around_sorted_countries
team_all_around_top3, team_all_around_sorted_countries = team_all_around_result(team12, apparatus_ls)
print(team_all_around_top3, team_all_around_sorted_countries)

['TUR', 'GER', 'NED'] [('TUR', 246.5714396346647), ('GER', 242.36717453490562), ('NED', 241.34444737943917), ('JPN', 239.97722718815194), ('HUN', 236.3837006052772), ('GBR', 235.32880248109092), ('UKR', 234.28393143196243), ('ESP', 231.65233495291747)]


In [231]:
#predict final round result for indiv all around
def indiv_all_around_result(teams, apparatus_ls, individual_all_around_top_24_athletes):
    team12 = teams[0]
    team36 = teams[1]
    individual_all_around_final_result = dict()
    for (country, name), score in individual_all_around_top_24_athletes:
        team = team12 if country in team12 else team36
        indiv_qual_score = score #team[country]["individual_all_around_qual_score"][name]
        #noise = np.random.normal(0, 1, indiv_qual_score.shape)
        noise = np.random.normal(0, 1)
        result = np.sum(indiv_qual_score)+noise
        individual_all_around_final_result[(country, name)] = result
        #print(team12[country_name]["team_12_all_around_final_result"]-team12[country_name]["qual_team_12_all_around_score"])
    individual_all_around_final_sorted = sorted(individual_all_around_final_result.items(), key=lambda x: x[1], reverse=True)
    top_3_athletes = [i for i, score in individual_all_around_final_sorted[:3]]


    return top_3_athletes, individual_all_around_final_sorted

indiv_all_around_top3,individual_all_around_final_sorted = indiv_all_around_result(teams, apparatus_ls, individual_all_around_top_24_athletes)


In [261]:
def qual_and_final_result_display(teams, indiv_all_around_top3,individual_all_around_final_sorted,\
    final_result_all_apparatus_dict, team_all_around_top3, team_all_around_sorted_countries):
    print("Team all around final round result:")
    for rank, (country,score) in enumerate(team_all_around_sorted_countries):
        print(rank+1, country, score)
    
    
    print("\nIndividual all around final round result:")
    for rank, ((country, name), score) in enumerate(individual_all_around_final_sorted):
        
        team = team12 if country in team12 else team36
        # pick some apparatus to get list of gymnasts name
        app = list(team12[country].keys())[0]
        gymnast_real_index = list(team12[country][app].index)
        print(rank+1, country, gymnast_real_index[name], score)
        
    print('\nEach Apparatus final round results:')
    for apparatus, result in final_result_all_apparatus_dict.items():
        top_8_athletes, sorted_athletes, top_3_athletes, sorted_athletes_final = result
        print(apparatus)
        for rank, ((country, name), score) in enumerate(sorted_athletes_final):
            team = team12 if country in team12 else team36
            # pick some apparatus to get list of gymnasts name
            app = list(team12[country].keys())[0]
            gymnast_real_index = list(team12[country][app].index)
            print(rank+1, country, gymnast_real_index[name], score)
        
        
    
qual_and_final_result_display(teams, indiv_all_around_top3,individual_all_around_final_sorted,\
    final_result_all_apparatus_dict, team_all_around_top3, team_all_around_sorted_countries)
    

Team all around final round result:
1 TUR 246.5714396346647
2 GER 242.36717453490562
3 NED 241.34444737943917
4 JPN 239.97722718815194
5 HUN 236.3837006052772
6 GBR 235.32880248109092
7 UKR 234.28393143196243
8 ESP 231.65233495291747

Individual all around final round result:
1 GBR 109 85.88098189592547
2 JPN 303 85.71648251461166
3 ITA 502 84.56802631708742
4 JPN 601 84.51257829318455
5 GER 350 84.21214552106179
6 ESP 475 84.01694971730639
7 GBR 266 83.57421847776227
8 NED 337 82.82274591348607
9 HUN 322 82.2448835751547
10 GER 435 81.85887733016834
11 FRA 456 81.70331827099166
12 TUR 221 81.58237249937301
13 FIN 158 79.99211799951786
14 ESP 269 79.6385038057307
15 UKR 414 78.83032929610438
16 NED 95 77.78340262956254
17 UKR 226 76.91923168364009
18 FRA 72 53.59958320198607
19 ITA 424 38.285557670747295
20 TUR 172 37.958015800096405
21 FIN 319 11.577587848214701
22 AUS 557 -0.9742365047492124
23 AUS 603 -1.3263443086041609

Each Apparatus final round results:
HB
1 TUR 16 15.3796296282

In [276]:
def medal_summarize_and_display(teams, indiv_all_around_top3,\
    final_result_all_apparatus_dict, team_all_around_top3):
    # 1:gold, 2:silver, 3: bronze
    medal_dict = {1:"Gold", 2:"Silver", 3: "Bronze"}
    medal_result_by_country = defaultdict(lambda: defaultdict(int))
    for rank, (country,name) in enumerate(indiv_all_around_top3):
        medal_result_by_country[country][rank+1]+=1
        
    for rank, country in enumerate(team_all_around_top3):
        medal_result_by_country[country][rank+1]+=1
   
    for apparatus, result in final_result_all_apparatus_dict.items():
        _,_, top_3_athletes, _ = result
        for rank, (country, name) in enumerate(top_3_athletes):
            medal_result_by_country[country][rank+1]+=1
    for country in medal_result_by_country:
        print('\n',country)
        for i,num_medal in medal_result_by_country[country].items():      
            print(medal_dict[i] + ": ", num_medal)

            
        
        
    
medal_summarize_and_display(teams, indiv_all_around_top3,\
    final_result_all_apparatus_dict, team_all_around_top3)


 GBR
Gold:  1
Bronze:  3

 JPN
Silver:  3
Gold:  2
Bronze:  1

 ITA
Bronze:  1
Gold:  1
Silver:  1

 TUR
Gold:  3

 GER
Silver:  2
Gold:  1

 NED
Bronze:  1
Silver:  1

 HUN
Bronze:  1

 UKR
Silver:  1
Bronze:  1
